### ISSUE TITLE
Task: Learn how to use Unity Game Engine

### ISSUE THREAD

**Issue by FarazPir** [Allen-ISD-Computer-Science/REPO_Platformer2D_2024#17]
Get a solid of understanding of how to use Unity Game Engine to create our game.

Supports #16

**Comment by SophieH8** [comment]
Downloaded and set up Unity. Created the initial game files.

**Comment by poofy-bananas** [comment]
Downloaded and set up Unity and started becoming familiar with the software

**Comment by FarazPir** [comment]
Supports #18
