### ISSUE TITLE
Task: Learn how to use Git/Github with Unity

### ISSUE THREAD

**Issue by FarazPir** [Allen-ISD-Computer-Science/REPO_Platformer2D_2024#18]
Learn how to work with Unity while keeping all files in the Git repository and keeping Github updated.

Supports #16

**Comment by FarazPir** [comment]
Potential Solution: Using WebDav mount our home drive to our computers, then download Unity on our computers, then just keep all the game files in our home drive, git commits can be managed in the terminal but the edits to the files will be done in Unity.

**Comment by FarazPir** [comment]
Progress has been halted due to technical difficulties with WebDav, once a workaround can be figured out then we can begin making commits

**Comment by EighthRisen** [comment]
Practiced using Github in another repository in terminal
https://github.com/battondl/git-demo

**Comment by FarazPir** [comment]
Current Solution: Instead of using Webdav, we're having Github/Git installed on our personal computers and cloning the repository locally.
@SophieH8 got this first set up, I then got it setup as well with some commits, with the help of @EighthRisen . @Shriya-Bansal and @poofy-bananas also learned and got the Unity and Github/Git setup.
