### ISSUE TITLE
Task: Develop an outline for the levels

### ISSUE THREAD

**Issue by FarazPir** [Allen-ISD-Computer-Science/REPO_Platformer2D_2024#19]
Create an outline that has the various levels, their order, their themes, cutscene placement, and any other important details about the levels such as the introduction of gameplay mechanics.

**Comment by FarazPir** [comment]
Supports #13

**Comment by Shriya-Bansal** [comment]
- Created parameters for each level.
- 8 levels total.
- Boss level at the end.
- Increases in difficulty as user progresses through each level.
- Pop ups with directions at the beginning of each level.
- Storyline breakdown (like Run 3) before level 1.

**Comment by poofy-bananas** [comment]
- created a theme for the levels
- created a general story that progresses as the levels develop
- established the setting for the levels and created the plan of their design

**Comment by SophieH8** [comment]
Created themes and ideas for each level.
https://docs.google.com/document/d/1Fgyq3IqtrQVzAqQ3ZzZVjSYkM69gFQo6SnS0qeXBjYY/edit?usp=sharing
