### ISSUE TITLE
Task: Find/create sprite sheets for enemies

### ISSUE THREAD

**Issue by SophieH8** [Allen-ISD-Computer-Science/REPO_Platformer2D_2024#29]
https://assetstore.unity.com/2d

**Comment by EighthRisen** [comment]
5 possible enemy sprites with recoloring listed in google drive, and fruit sheet.

**Comment by FarazPir** [comment]
Another good site for sprites https://craftpix.net/freebies/

**Comment by EighthRisen** [comment]
Now 15+ enemy sprites and 10 backgrounds in another doc
https://drive.google.com/drive/folders/1sNWdLmPR-t-r4ShIe7l5WuC4sFwDJdGI

**Comment by FarazPir** [comment]
useful video 
https://youtu.be/QzQq4os3-nU?si=7MdlxsAeAmpBmMO_

**Comment by Shriya-Bansal** [comment]
https://docs.google.com/presentation/d/1qxcMQ0PFzFnlnHHCB81c5oW3GGiwzbL4wmOPjOQO3B4/edit?usp=sharing

Link to slideshow featuring enemy sprites/enemy roles for levels 1-8.
