### ISSUE TITLE
Task: Find and create sign pointing to next level (Cauliflower Clearing)

### ISSUE THREAD

**Issue by SophieH8** [Allen-ISD-Computer-Science/REPO_Platformer2D_2024#34]

**Comment by Shriya-Bansal** [comment]
![Cauliflower_Clearing_Sign](https://github.com/Allen-ISD-Computer-Science/REPO_Platformer2D_2024/assets/111066642/f046b911-f048-4e7b-928d-afb0eceff9f3)

Created Cauliflower Clearing Signboard to be placed at the end of Level 1.

**Comment by Shriya-Bansal** [comment]
Couldn't connect Unity to Github, so created the signboard separately, downloaded it as a JPEG file and uploaded to Github.
Will work on getting Unity synced with Github to commit all changes in the future.

**Comment by Shriya-Bansal** [comment]
**Update:** Added arrow to Cauliflower signboard directing to Level 2.

![Cauliflower signboard](https://github.com/Allen-ISD-Computer-Science/REPO_Platformer2D_2024/assets/111066642/7b8896e0-00ce-4190-9ce3-443f6829334d)

**Comment by Shriya-Bansal** [comment]
Correction/Final change: Changed image background from white to clear.



![Image](https://github.com/Allen-ISD-Computer-Science/REPO_Platformer2D_2024/assets/111066642/02463a4d-ce55-4c30-ab60-57eb39f981a4)
