### ISSUE TITLE
Task: Create falling sprite for Ava Avocado

### ISSUE THREAD

**Issue by SophieH8** [Allen-ISD-Computer-Science/REPO_Platformer2D_2024#36]

**Comment by poofy-bananas** [comment]
Created a falling sprite for Ava Avocado in the graphics editor app (GIMP). Wasn't able to upload to Unity due to connecting issues.

![Image](https://github.com/Allen-ISD-Computer-Science/REPO_Platformer2D_2024/assets/111151892/dc54dc28-8031-4883-8cd8-57926af24a16)

.
