### ISSUE TITLE
Task: Create jumping sprite for Ava Avocado

### ISSUE THREAD

**Issue by SophieH8** [Allen-ISD-Computer-Science/REPO_Platformer2D_2024#37]

**Comment by poofy-bananas** [comment]
Created a jumping sprite using GIMP (a graphics editor) but wasn't able to connect it to Unity yet due to connectivity issues. 

![Image](https://github.com/Allen-ISD-Computer-Science/REPO_Platformer2D_2024/assets/111151892/c73b8036-0656-4520-8726-9daabbb4f818)
