### ISSUE TITLE
Task: Create a hurt/injured sprite sheet for Ava Avocado

### ISSUE THREAD

**Issue by SophieH8** [Allen-ISD-Computer-Science/REPO_Platformer2D_2024#42]

**Comment by poofy-bananas** [comment]
Created hurt/injured sprite sheet for Ava Avocado on GIMP. May need to make a few adjustments later on. 

![Image](https://github.com/Allen-ISD-Computer-Science/REPO_Platformer2D_2024/assets/111151892/0ef04a9c-a9d3-40a2-b395-572ac2daae0f)
