### ISSUE TITLE
Task: add an attackable dummy

### ISSUE THREAD

**Issue by SophieH8** [Allen-ISD-Computer-Science/REPO_Platformer2D_2024#51]

**Comment by FarazPir** [comment]
Going to have to be pushed to the next sprint since creating a dummy requires creating a health system which will take more time.

**Comment by FarazPir** [comment]
Dummy will have to be pushed back again due to enemies needing more work done on their health systems, since there's will be slightly different from player health systems.

**Comment by FarazPir** [comment]
https://www.youtube.com/watch?v=WmwS4dpKLZg
