### ISSUE TITLE
Task: Draw background for start screen

### ISSUE THREAD

**Issue by SophieH8** [Allen-ISD-Computer-Science/REPO_Platformer2D_2024#59]

**Comment by poofy-bananas** [comment]
I wasn't able to make much progress as I was sick the first day, but started planning and finding reference pictures and elements to plan the idea: https://docs.google.com/presentation/d/17GRtG8whfwQ59r71XIK13qPIjTCd8dhsNIV4SHTGZqc/edit?usp=sharing

**Comment by poofy-bananas** [comment]
Finished the start screen ( finally :) )- need to add animations to objects in the background and finalize the title as well. 

Background with planning for title: 
![Image](https://github.com/Allen-ISD-Computer-Science/REPO_Platformer2D_2024/assets/111151892/1b8d4041-40f8-45e7-a3e9-aea8f1fd732d)
