### ISSUE TITLE
Task: Add space for cut screen between levels

### ISSUE THREAD

**Issue by SophieH8** [Allen-ISD-Computer-Science/REPO_Platformer2D_2024#85]

**Comment by FarazPir** [comment]
This task was not completed this sprint because my other task from this Sprint (#84) took longer than anticipated, so this task will have to be moved to the next Sprint.

**Comment by FarazPir** [comment]
Using this tutorial
https://youtu.be/0soGRKtpJuA?si=Ev8g-N_94s67bMr3
