### ISSUE TITLE
Task: Develop an outline for the game's storyline

### ISSUE THREAD

**Issue by SophieH8** [Allen-ISD-Computer-Science/REPO_Platformer2D_2024#9]
Supports Story #6

**Comment by SophieH8** [comment]
Created an outline on google docs of the story. 
https://docs.google.com/document/d/1Fgyq3IqtrQVzAqQ3ZzZVjSYkM69gFQo6SnS0qeXBjYY/edit?usp=sharing

**Comment by poofy-bananas** [comment]
- helped create an elaborate and plausible story as the game progresses
- incorporated a theme into the story
- planned cutscenes in between levels to support the story
